### ISSUE TITLE
Possible to test voice solutions without the LLM part?

### ISSUE THREAD

**Issue by chrisbward** [bephrem1/vocalized.dev#17]
Just keep to try out different voices coming out of the demos - suggestion to allow user to enter a message instead of leveraging LLMs / grabbing keys

**Comment by bephrem1** [comment]
(if I understand correctly) Yes, I want to have a tab dedicated to split testing just text-to-speech providers' voices, all at once w/ the same message.

The end-state for the playground is 3 tabs: "conversation" (real-time), "speech" (text-to-speech), & "transcription" (speech-to-text). As real-time conversation moves to primarily audio-to-audio models it will make less sense to have interest in testing each layer of this stack. You'd just use the provider with the best audio model (& they would offer different voices).
